package org.itson.disenosoftware.presentacion;

import org.itson.disenosoftware.navegacion.INavegacion;
import org.itson.disenosoftware.navegacion.Navegacion;

/**
 *
 * @author José Karim Franco Valencia - 245138
 * @author Kimberli Joana Martinez Sandoval - 244802
 * @author Víctor Humberto Encinas Guzmán - 244821
 * @author José Ángel Huerta Amparán - 245345
 * @author Alexa Maria Picos Valenzuela - 244893
 */
public class FrmOpcionesCliente extends javax.swing.JFrame {

    INavegacion navegacion;
    /** Creates new form FrmOpcionesCliente */
    public FrmOpcionesCliente() {
        navegacion = new Navegacion();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        logoRosa1 = new javax.swing.JLabel();
        logoRosa2 = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        btnClienteRegistrado = new javax.swing.JButton();
        btnClienteNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEncabezado.setBackground(new java.awt.Color(64, 53, 44));
        panelEncabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEncabezado.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(242, 224, 201));
        lblEncabezado.setText("EL ROSAL");
        panelEncabezado.add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 30, -1, -1));

        logoRosa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconRosa.png"))); // NOI18N
        panelEncabezado.add(logoRosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 64, 64));

        logoRosa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconRosa.png"))); // NOI18N
        panelEncabezado.add(logoRosa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 64, 64));

        getContentPane().add(panelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        panelOpciones.setBackground(new java.awt.Color(242, 224, 201));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClienteRegistrado.setBackground(new java.awt.Color(64, 53, 44));
        btnClienteRegistrado.setFont(new java.awt.Font("Amazon Ember Light", 0, 36)); // NOI18N
        btnClienteRegistrado.setForeground(new java.awt.Color(242, 224, 201));
        btnClienteRegistrado.setText("CLIENTE REGISTRADO");
        btnClienteRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteRegistradoActionPerformed(evt);
            }
        });
        panelOpciones.add(btnClienteRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 400, 100));

        btnClienteNuevo.setBackground(new java.awt.Color(64, 53, 44));
        btnClienteNuevo.setFont(new java.awt.Font("Amazon Ember Light", 0, 36)); // NOI18N
        btnClienteNuevo.setForeground(new java.awt.Color(242, 224, 201));
        btnClienteNuevo.setText("CLIENTE NUEVO");
        btnClienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteNuevoActionPerformed(evt);
            }
        });
        panelOpciones.add(btnClienteNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 400, 100));

        getContentPane().add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteNuevoActionPerformed
        navegacion.cambiarFrmRegistroCliente(this);
    }//GEN-LAST:event_btnClienteNuevoActionPerformed

    private void btnClienteRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteRegistradoActionPerformed
        navegacion.cambiarFrmBuscarCliente(this);
    }//GEN-LAST:event_btnClienteRegistradoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteNuevo;
    private javax.swing.JButton btnClienteRegistrado;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel logoRosa1;
    private javax.swing.JLabel logoRosa2;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables

}
