package org.itson.disenosoftware.presentacion;

import org.itson.disenosoftware.navegacion.INavegacion;
import org.itson.disenosoftware.navegacion.Navegacion;
import org.itson.disenosoftware.negocio.dtos.ClienteNuevoDTO;
import org.itson.disenosoftware.negocio.subsistemas.cliente.FAdminClientes;
import org.itson.disenosoftware.negocio.subsistemas.cliente.IFAdminClientes;

/**
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 244802
 */
public class FrmRegistroCliente extends javax.swing.JFrame {

    INavegacion navegacion;
    ClienteNuevoDTO clienteDTO;
    /** Creates new form FrmOpcionesCliente */
    public FrmRegistroCliente() {
        navegacion = new Navegacion();
        clienteDTO = new ClienteNuevoDTO();
        initComponents();
    }

    private void guardar(){
        
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        String correo = txtCorreo.getText();
        String telefono = txtTelefono.getText();
        
        clienteDTO.setNombres(nombre);
        clienteDTO.setApellidos(apellidos);
        clienteDTO.setCorreo(correo);
        clienteDTO.setTelefono(telefono);
        
        IFAdminClientes adminClientes = new FAdminClientes();
        adminClientes.registrarCliente(clienteDTO);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        logoRosa1 = new javax.swing.JLabel();
        logoRosa2 = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblTituloSeccion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 580));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEncabezado.setBackground(new java.awt.Color(64, 53, 44));
        panelEncabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEncabezado.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(242, 224, 201));
        lblEncabezado.setText("EL ROSAL");
        panelEncabezado.add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 30, -1, -1));

        logoRosa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconRosa.png"))); // NOI18N
        panelEncabezado.add(logoRosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 64, 64));

        logoRosa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconRosa.png"))); // NOI18N
        panelEncabezado.add(logoRosa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 64, 64));

        getContentPane().add(panelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        panelOpciones.setBackground(new java.awt.Color(242, 224, 201));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setBackground(new java.awt.Color(242, 224, 201));
        txtNombre.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(34, 33, 33));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 53, 44), 2));
        panelOpciones.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 400, 40));

        lblTituloSeccion.setFont(new java.awt.Font("Amazon Ember", 1, 48)); // NOI18N
        lblTituloSeccion.setForeground(new java.awt.Color(64, 53, 44));
        lblTituloSeccion.setText("Registro cliente:");
        panelOpciones.add(lblTituloSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        lblNombre.setFont(new java.awt.Font("Amazon Ember", 1, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(64, 53, 44));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombre.setText("Nombre:");
        panelOpciones.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 200, 38));

        lblApellidos.setFont(new java.awt.Font("Amazon Ember", 1, 24)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(64, 53, 44));
        lblApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellidos.setText("Apellidos:");
        panelOpciones.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, 38));

        txtApellidos.setBackground(new java.awt.Color(242, 224, 201));
        txtApellidos.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(34, 33, 33));
        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 53, 44), 2));
        panelOpciones.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 400, 40));

        lblCorreo.setFont(new java.awt.Font("Amazon Ember", 1, 24)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(64, 53, 44));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreo.setText("Correo electronico:");
        panelOpciones.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 230, 38));

        txtCorreo.setBackground(new java.awt.Color(242, 224, 201));
        txtCorreo.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(34, 33, 33));
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 53, 44), 2));
        panelOpciones.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 400, 40));

        lblTelefono.setFont(new java.awt.Font("Amazon Ember", 1, 24)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(64, 53, 44));
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefono.setText("Teléfono:");
        panelOpciones.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 200, 38));

        txtTelefono.setBackground(new java.awt.Color(242, 224, 201));
        txtTelefono.setFont(new java.awt.Font("Amazon Ember Light", 0, 20)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(34, 33, 33));
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 53, 44), 2));
        panelOpciones.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 400, 40));

        btnCancelar.setBackground(new java.awt.Color(64, 53, 44));
        btnCancelar.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(242, 224, 201));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelOpciones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 160, 50));

        btnAgregar.setBackground(new java.awt.Color(64, 53, 44));
        btnAgregar.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(242, 224, 201));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorderPainted(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panelOpciones.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 160, 50));

        getContentPane().add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        guardar();
        navegacion.cambiarFrmTipoOrden(this, clienteDTO);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        navegacion.cambiarFrmTipoOrden(this, clienteDTO);
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloSeccion;
    private javax.swing.JLabel logoRosa1;
    private javax.swing.JLabel logoRosa2;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
