/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package org.itson.disenosoftware.presentacion;

/**
 *
 * @author José Karim Franco Valencia - 245138
 * @author Jesus Rene Gonzalez Castro - 247336
 * @author Gael Rafael Castro Molina - 244802
 */
public class FrmTipoOrden extends javax.swing.JFrame {

    /** Creates new form FrmOpcionesCliente */
    public FrmTipoOrden() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado = new javax.swing.JPanel();
        lblEncabezado = new javax.swing.JLabel();
        logoRosa1 = new javax.swing.JLabel();
        logoRosa2 = new javax.swing.JLabel();
        panelOpciones = new javax.swing.JPanel();
        lblTituloSeccion = new javax.swing.JLabel();
        lblOpciones1 = new javax.swing.JLabel();
        lblOpciones2 = new javax.swing.JLabel();
        lblOpciones3 = new javax.swing.JLabel();
        panelOpcion3 = new javax.swing.JPanel();
        btnOpcionFoto1 = new javax.swing.JButton();
        panelOpcion2 = new javax.swing.JPanel();
        btnOpcionFoto = new javax.swing.JButton();
        panelOpcion1 = new javax.swing.JPanel();
        btnOpcionMarco = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEncabezado.setBackground(new java.awt.Color(64, 53, 44));
        panelEncabezado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEncabezado.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        lblEncabezado.setForeground(new java.awt.Color(242, 224, 201));
        lblEncabezado.setText("EL ROSAL");
        panelEncabezado.add(lblEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 30, -1, -1));

        logoRosa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconRosa.png"))); // NOI18N
        panelEncabezado.add(logoRosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 64, 64));

        logoRosa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconRosa.png"))); // NOI18N
        panelEncabezado.add(logoRosa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 64, 64));

        getContentPane().add(panelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 100));

        panelOpciones.setBackground(new java.awt.Color(242, 224, 201));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloSeccion.setFont(new java.awt.Font("Amazon Ember", 1, 48)); // NOI18N
        lblTituloSeccion.setForeground(new java.awt.Color(64, 53, 44));
        lblTituloSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSeccion.setText("Tipo de orden:");
        panelOpciones.add(lblTituloSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 800, -1));

        lblOpciones1.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblOpciones1.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones1.setText("Servicio completo");
        panelOpciones.add(lblOpciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 275, -1, -1));

        lblOpciones2.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblOpciones2.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones2.setText("Enmarcar una foto");
        panelOpciones.add(lblOpciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 135, -1, -1));

        lblOpciones3.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblOpciones3.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones3.setText("Restaurar una foto");
        panelOpciones.add(lblOpciones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 205, -1, -1));

        panelOpcion3.setBackground(new java.awt.Color(242, 224, 201));
        panelOpcion3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 53, 44), 2, true));
        panelOpcion3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpcionFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconX.png"))); // NOI18N
        btnOpcionFoto1.setBorder(null);
        btnOpcionFoto1.setBorderPainted(false);
        btnOpcionFoto1.setContentAreaFilled(false);
        btnOpcionFoto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionFoto1.setFocusPainted(false);
        btnOpcionFoto1.setFocusable(false);
        panelOpcion3.add(btnOpcionFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelOpciones.add(panelOpcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 50, 50));

        panelOpcion2.setBackground(new java.awt.Color(242, 224, 201));
        panelOpcion2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 53, 44), 2, true));
        panelOpcion2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpcionFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconX.png"))); // NOI18N
        btnOpcionFoto.setBorder(null);
        btnOpcionFoto.setBorderPainted(false);
        btnOpcionFoto.setContentAreaFilled(false);
        btnOpcionFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionFoto.setFocusPainted(false);
        btnOpcionFoto.setFocusable(false);
        panelOpcion2.add(btnOpcionFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelOpciones.add(panelOpcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 50, 50));

        panelOpcion1.setBackground(new java.awt.Color(242, 224, 201));
        panelOpcion1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 53, 44), 2, true));
        panelOpcion1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpcionMarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconX.png"))); // NOI18N
        btnOpcionMarco.setBorder(null);
        btnOpcionMarco.setBorderPainted(false);
        btnOpcionMarco.setContentAreaFilled(false);
        btnOpcionMarco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpcionMarco.setFocusPainted(false);
        btnOpcionMarco.setFocusable(false);
        btnOpcionMarco.setLabel("");
        panelOpcion1.add(btnOpcionMarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panelOpciones.add(panelOpcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 50, 50));

        btnCancelar.setBackground(new java.awt.Color(64, 53, 44));
        btnCancelar.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(242, 224, 201));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        panelOpciones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 160, 50));

        btnContinuar.setBackground(new java.awt.Color(64, 53, 44));
        btnContinuar.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(242, 224, 201));
        btnContinuar.setText("Continuar");
        btnContinuar.setBorderPainted(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        panelOpciones.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 160, 50));

        getContentPane().add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1000, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnOpcionFoto;
    private javax.swing.JButton btnOpcionFoto1;
    private javax.swing.JButton btnOpcionMarco;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblOpciones1;
    private javax.swing.JLabel lblOpciones2;
    private javax.swing.JLabel lblOpciones3;
    private javax.swing.JLabel lblTituloSeccion;
    private javax.swing.JLabel logoRosa1;
    private javax.swing.JLabel logoRosa2;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelOpcion1;
    private javax.swing.JPanel panelOpcion2;
    private javax.swing.JPanel panelOpcion3;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables

}
